### Preflight OPTIONS request for CORS
Origin: https://destined-separately-fox.ngrok-free.app
Access-Control-Request-Method: POST, GET, PUT, DELETE
Access-Control-Request-Headers: Content-Type, Authorization

### Get DATA
GET https://stirred-guided-bullfrog.ngrok-free.app/admin
# Authorization: Bearer

### Register
POST https://stirred-guided-bullfrog.ngrok-free.app/register
Content-Type: application/json

### Login
POST https://stirred-guided-bullfrog.ngrok-free.app/login
Content-Type: application/json

### Refresh Token
GET  https://stirred-guided-bullfrog.ngrok-free.app/token

### Logout
DELETE  https://stirred-guided-bullfrog.ngrok-free.app/logout

### GET DATA TABLE BENGKEL WITHOUT LOGIN
GET https://stirred-guided-bullfrog.ngrok-free.app/bengkel-data

### GET DATA TABLE BENGKEL
GET https://stirred-guided-bullfrog.ngrok-free.app/bengkel
Authorization: Bearer 

### GET DATA TABLE BENGKEL BY ID
GET https://stirred-guided-bullfrog.ngrok-free.app/bengkel/5

### INSERT DATA TABLE BENGKEL
POST https://stirred-guided-bullfrog.ngrok-free.app/bengkel/add
Content-Type: application/json
Authorization: Bearer 

### Refresh Token data bengkel
GET  https://stirred-guided-bullfrog.ngrok-free.app/token-bengkel

### Get data user
GET https://stirred-guided-bullfrog.ngrok-free.app/user
Authorization: Bearer 

### Registers users
POST https://stirred-guided-bullfrog.ngrok-free.app/register-user
Content-Type: application/json


### Login user
POST https://stirred-guided-bullfrog.ngrok-free.app/login-user
Content-Type: application/json


### Refresh Token User
GET  https://stirred-guided-bullfrog.ngrok-free.app/token-user

### Get data Article
GET https://stirred-guided-bullfrog.ngrok-free.app/artikel
